model:
  dest: model.BirdClf
  paras:
    embed_size: 525

data:
  img_size: 224
  data_path: 'data'
  augment: True
  resized_crop: True
  herizon_flip: True
  vertical_flip: True
  random_affine: False
  batch_size: 128
  num_workers: 8

loss:
  dest: loss.CrossEntropyLoss
  weight: None
  reduction: 'mean'
  label_smoothing: 0.2

optimizer:
  type: 'SGD'  # AdamW, SGD, Adam
  lr: 2e-4
  weight_decay: 1e-3
  momentum: 0.9

scheduler:
  type: 'StepLR'  # CosineAnnealingLR, StepLR 
  T_max: 50
  eta_min: 1e-7
  step_size: 11
  gamma: 0.1
  
resume: False
ckpt_path: ''
max_epochs: 50
val_interval: 1
accuracy_thre: 5
random_seed: 42
