model:
  dest: model.FaceRecg
  paras:
    ckpt_path: 'log/ckpt/mtcnn_last_acc_0.8693.pth'
    save_ckpt_path: log/ckpt
    embed_size: 128


data:
  batch_size: 60
  num_workers: 8
  test:
    dest: dataset.TestDataset
    paras: 
      align_type: 'mtcnn'
      align_size: 112, 96
  validation:
    dest: dataset.TripletValDataset
    paras: 
      pairs_num: 50000
      align_type: 'mtcnn'
      align_size: 112, 96
