model:
  dest: model.BirdClf_R
  paras:
    embed_size: 525

data:
  img_size: 224
  data_path: 'data'
  augment: True
  batch_size: 256
  num_workers: 8

loss:
  dest: loss.CrossEntropyLoss
  weight: None
  reduction: 'mean'
  label_smoothing: 0.2

optimizer:
  type: 'AdamW'  # AdamW, SGD, Adam
  lr: 1e-3
  weight_decay: 1e-4
  momentum: 0.9

scheduler:
  type: 'ReduceLROnPlateau'  # ReduceLROnPlateau CosineAnnealingLR, StepLR 
  mode: 'min'
  verbose: True
  factor: 0.1
  patience: 15
  T_max: 50
  eta_min: 1e-7
  step_size: 10
  gamma: 0.1
  
resume: False
ckpt_path: ''
max_epochs: 50
val_interval: 1
accuracy_thre: 5
random_seed: 42
